version: '3'
services:
        mysql-db:
                image: mariadb
                #restart: always
                #command: --default-authentication-plugin=mysql_native_password
                environment:
                        MARIADB_ROOT_PASSWORD: root
                        MARIADB_USER: qt-rss-user
                        MARIADB_PASSWORD: qt-rss-user-password
                        MARIADB_DATABASE: qt-rss
                ports:
                        - 3306:3306

        adminer:
                image: adminer
                restart: always
                ports:
                        - 8080:8080

